<script lang="ts">
  import type {
    // CellHyperlinkFormat,
    MetaRun,
    NormalCellDescriptor,
  } from "@datadocs/canvas-datagrid-ng";
  import { isHyperlinkDataFormat } from "@datadocs/canvas-datagrid-ng/lib/data/formatters/util";
  import HyperlinkCard from "../../hyperlink/hyperlink-card/HyperlinkCard.svelte";
  import { getHyperlinkRunsFromDataFormat } from "../util";

  export let data: NormalCellDescriptor;

  function getLinkRunFromHyperlinkDataFormat(
    cell: NormalCellDescriptor
  ): MetaRun {
    const format = cell.dataFormat;
    if (isHyperlinkDataFormat(format)) {
      let cellValue = cell.value;
      if (cell.value && typeof cell.value === "object") {
        // variant cell value
        cellValue = cell.value?.value;
      }
      if (cell?.meta?.parserData) {
        // free form cell value
        cellValue = cell.meta.parserData.value;
      }

      if (format.style?.startsWith("l")) {
        return { ref: cellValue, label: cell.linkLabel ?? null };
      } else if (format.style?.startsWith("r") && cell.linkRef) {
        return { ref: cell.linkRef, label: cellValue };
      }
    }
    return null;
  }

  $: hyperlinkDataFormat = isHyperlinkDataFormat(data.dataFormat);
  $: runs = hyperlinkDataFormat
    ? getHyperlinkRunsFromDataFormat(data) ?? null
    : null;
</script>

{#if runs && runs.length > 0}
  <div class="max-w-[320px] px-3 py-1">
    <div class="flex flex-col gap-1 max-h-full overflow-y-auto">
      {#each runs as run}
        <HyperlinkCard
          gridCellRowIndex={data.rowIndex}
          gridCellColumnIndex={data.columnIndex}
          linkRun={run}
          readonly={true}
        />
      {/each}
    </div>

    {#if hyperlinkDataFormat}
      <div
        class="py-1 text-12px font-medium text-dark-100 select-text"
      >
        This link is auto-generated by your Custom Data-Format. To change it, go
        to the Data-Format menu.
      </div>
    {/if}
  </div>
{/if}
