#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

[ -f "$1" ] || exit 0;
awk '{ if(index(tolower($0),"wip")==1)exit 0; exit 1;}' "$1" && exit 0;

project_root="$(dirname "$0")/..";
if ! test -d "${project_root}/node_modules"; then
	project_root="${project_root}/..";
	test -d "${project_root}/node_modules" || exit 0;
fi

commitlint="${project_root}/node_modules/.bin/commitlint";
test -x "$commitlint" || exit 0;
"$commitlint" --edit "$1";
